/* tslint:disable */
/* eslint-disable */
/**
 * business-data-api
 * business-data-api API definitions
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { DataEntry } from '../models';
/**
 * DataEntryApi - axios parameter creator
 * @export
 */
export const DataEntryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get data entries for site
         * @summary Get all data entries for site
         * @param {string} siteId Site Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDataEntriesBySiteUsingGET: async (siteId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'siteId' is not null or undefined
            if (siteId === null || siteId === undefined) {
                throw new RequiredError('siteId','Required parameter siteId was null or undefined when calling getDataEntriesBySiteUsingGET.');
            }
            const localVarPath = `/v1/site/{siteId}/data-entries`
                .replace(`{${"siteId"}}`, encodeURIComponent(String(siteId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_token_sec_key required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("X-API-Token")
                    : await configuration.apiKey;
                localVarHeaderParameter["X-API-Token"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DataEntryApi - functional programming interface
 * @export
 */
export const DataEntryApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Get data entries for site
         * @summary Get all data entries for site
         * @param {string} siteId Site Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDataEntriesBySiteUsingGET(siteId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<DataEntry>>>> {
            const localVarAxiosArgs = await DataEntryApiAxiosParamCreator(configuration).getDataEntriesBySiteUsingGET(siteId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DataEntryApi - factory interface
 * @export
 */
export const DataEntryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Get data entries for site
         * @summary Get all data entries for site
         * @param {string} siteId Site Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDataEntriesBySiteUsingGET(siteId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<DataEntry>>> {
            return DataEntryApiFp(configuration).getDataEntriesBySiteUsingGET(siteId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DataEntryApi - object-oriented interface
 * @export
 * @class DataEntryApi
 * @extends {BaseAPI}
 */
export class DataEntryApi extends BaseAPI {
    /**
     * Get data entries for site
     * @summary Get all data entries for site
     * @param {string} siteId Site Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DataEntryApi
     */
    public async getDataEntriesBySiteUsingGET(siteId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<DataEntry>>> {
        return DataEntryApiFp(this.configuration).getDataEntriesBySiteUsingGET(siteId, options).then((request) => request(this.axios, this.basePath));
    }
}
