/* tslint:disable */
/* eslint-disable */
/**
 * business-data-api
 * business-data-api API definitions
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { StaffAttendance } from '../models';
/**
 * StaffAttendanceApi - axios parameter creator
 * @export
 */
export const StaffAttendanceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get staff attendances for site
         * @summary Get all staff attendances for site
         * @param {string} siteId Site Id
         * @param {string} [id] Pass attendance id as offset to receive the last or next n attendance entries
         * @param {string} [order] Order of attendances, options: ASC (oldest first) / DESC (newest first) default: DESC
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStaffAttendanceBySiteUsingGET: async (siteId: string, id?: string, order?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'siteId' is not null or undefined
            if (siteId === null || siteId === undefined) {
                throw new RequiredError('siteId','Required parameter siteId was null or undefined when calling getStaffAttendanceBySiteUsingGET.');
            }
            const localVarPath = `/v1/site/{siteId}/staff-attendances`
                .replace(`{${"siteId"}}`, encodeURIComponent(String(siteId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_token_sec_key required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("X-API-Token")
                    : await configuration.apiKey;
                localVarHeaderParameter["X-API-Token"] = localVarApiKeyValue;
            }

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StaffAttendanceApi - functional programming interface
 * @export
 */
export const StaffAttendanceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Get staff attendances for site
         * @summary Get all staff attendances for site
         * @param {string} siteId Site Id
         * @param {string} [id] Pass attendance id as offset to receive the last or next n attendance entries
         * @param {string} [order] Order of attendances, options: ASC (oldest first) / DESC (newest first) default: DESC
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStaffAttendanceBySiteUsingGET(siteId: string, id?: string, order?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<StaffAttendance>>>> {
            const localVarAxiosArgs = await StaffAttendanceApiAxiosParamCreator(configuration).getStaffAttendanceBySiteUsingGET(siteId, id, order, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * StaffAttendanceApi - factory interface
 * @export
 */
export const StaffAttendanceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Get staff attendances for site
         * @summary Get all staff attendances for site
         * @param {string} siteId Site Id
         * @param {string} [id] Pass attendance id as offset to receive the last or next n attendance entries
         * @param {string} [order] Order of attendances, options: ASC (oldest first) / DESC (newest first) default: DESC
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStaffAttendanceBySiteUsingGET(siteId: string, id?: string, order?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<StaffAttendance>>> {
            return StaffAttendanceApiFp(configuration).getStaffAttendanceBySiteUsingGET(siteId, id, order, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * StaffAttendanceApi - object-oriented interface
 * @export
 * @class StaffAttendanceApi
 * @extends {BaseAPI}
 */
export class StaffAttendanceApi extends BaseAPI {
    /**
     * Get staff attendances for site
     * @summary Get all staff attendances for site
     * @param {string} siteId Site Id
     * @param {string} [id] Pass attendance id as offset to receive the last or next n attendance entries
     * @param {string} [order] Order of attendances, options: ASC (oldest first) / DESC (newest first) default: DESC
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StaffAttendanceApi
     */
    public async getStaffAttendanceBySiteUsingGET(siteId: string, id?: string, order?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<StaffAttendance>>> {
        return StaffAttendanceApiFp(this.configuration).getStaffAttendanceBySiteUsingGET(siteId, id, order, options).then((request) => request(this.axios, this.basePath));
    }
}
