/* tslint:disable */
/* eslint-disable */
/**
 * business-data-api
 * business-data-api API definitions
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CancelReason } from './cancel-reason';
import { InvoiceCanceledItem } from './invoice-canceled-item';
import { InvoiceDiscount } from './invoice-discount';
import { InvoiceItem } from './invoice-item';
import { InvoiceItemDiscount } from './invoice-item-discount';
import { InvoiceItemSurcharge } from './invoice-item-surcharge';
import { InvoiceSurcharge } from './invoice-surcharge';
import { MainGroup } from './main-group';
import { Product } from './product';
import { ProductGroup } from './product-group';
/**
 * 
 * @export
 * @interface DetailedInvoice
 */
export interface DetailedInvoice {
    /**
     * List of cancellation reasons for invoice canceled items
     * @type {Array<CancelReason>}
     * @memberof DetailedInvoice
     */
    cancelReasons?: Array<CancelReason>;
    /**
     * List canceled items of the invoice
     * @type {Array<InvoiceCanceledItem>}
     * @memberof DetailedInvoice
     */
    canceledItems?: Array<InvoiceCanceledItem>;
    /**
     * Reference id of the cash register that created the invoice.
     * @type {string}
     * @memberof DetailedInvoice
     */
    cashRegisterId?: string;
    /**
     * The ISO name of the currency used in this invoice (currently only EUR supported)
     * @type {string}
     * @memberof DetailedInvoice
     */
    currency?: string;
    /**
     * List of discounts contained within the invoice
     * @type {Array<InvoiceDiscount>}
     * @memberof DetailedInvoice
     */
    discounts?: Array<InvoiceDiscount>;
    /**
     * Unique id of this invoice
     * @type {string}
     * @memberof DetailedInvoice
     */
    invoiceId?: string;
    /**
     * POS-relevant number of the invoice
     * @type {number}
     * @memberof DetailedInvoice
     */
    invoiceNumber?: number;
    /**
     * List of discounts for invoice items
     * @type {Array<InvoiceItemDiscount>}
     * @memberof DetailedInvoice
     */
    itemDiscounts?: Array<InvoiceItemDiscount>;
    /**
     * List of surcharges for invoice items
     * @type {Array<InvoiceItemSurcharge>}
     * @memberof DetailedInvoice
     */
    itemSurcharges?: Array<InvoiceItemSurcharge>;
    /**
     * List of items of the invoice
     * @type {Array<InvoiceItem>}
     * @memberof DetailedInvoice
     */
    items?: Array<InvoiceItem>;
    /**
     * List of main groups which are contained in the invoice items
     * @type {Array<MainGroup>}
     * @memberof DetailedInvoice
     */
    mainGroups?: Array<MainGroup>;
    /**
     * The numeric total net amount of this invoice
     * @type {number}
     * @memberof DetailedInvoice
     */
    netTotal?: number;
    /**
     * List of product groups they contained in the invoice items
     * @type {Array<ProductGroup>}
     * @memberof DetailedInvoice
     */
    productGroups?: Array<ProductGroup>;
    /**
     * List of products they contained in the invoice items
     * @type {Array<Product>}
     * @memberof DetailedInvoice
     */
    products?: Array<Product>;
    /**
     * Reference id to the site
     * @type {string}
     * @memberof DetailedInvoice
     */
    siteId?: string;
    /**
     * List of surcharges contained within the invoice
     * @type {Array<InvoiceSurcharge>}
     * @memberof DetailedInvoice
     */
    surcharges?: Array<InvoiceSurcharge>;
    /**
     * POS-relevant number of table of the invoice
     * @type {number}
     * @memberof DetailedInvoice
     */
    tableNumber?: number;
    /**
     * The numeric total gross amount of this invoice
     * @type {number}
     * @memberof DetailedInvoice
     */
    total?: number;
    /**
     * Date and time of the invoice
     * @type {string}
     * @memberof DetailedInvoice
     */
    transactionAt?: string;
    /**
     * The type of the transaction
     * @type {string}
     * @memberof DetailedInvoice
     */
    transactionType?: DetailedInvoiceTransactionTypeEnum;
    /**
     * POS-relevant number of waiter who has created the invoice
     * @type {number}
     * @memberof DetailedInvoice
     */
    waiterNumber?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum DetailedInvoiceTransactionTypeEnum {
    CANCELLEDINVOICE = 'CANCELLED_INVOICE',
    INVOICE = 'INVOICE'
}

