/* tslint:disable */
/* eslint-disable */
/**
 * business-data-api
 * business-data-api API definitions
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ManagedArticle
 */
export interface ManagedArticle {
    /**
     * The name of the managed article
     * @type {string}
     * @memberof ManagedArticle
     */
    managedArticleName?: string;
    /**
     * The number of the managed article
     * @type {number}
     * @memberof ManagedArticle
     */
    managedArticleNo?: number;
    /**
     * The price of the managed article
     * @type {number}
     * @memberof ManagedArticle
     */
    price?: number;
    /**
     * The entry values of the managed article
     * @type {Array<number>}
     * @memberof ManagedArticle
     */
    values?: Array<number>;
    /**
     * The writeable values for the entry values
     * @type {Array<boolean>}
     * @memberof ManagedArticle
     */
    writeableByInputMask?: Array<boolean>;
}
