/* tslint:disable */
/* eslint-disable */
/**
 * business-data-api
 * business-data-api API definitions
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProductGroup
 */
export interface ProductGroup {
    /**
     * The name of the product group
     * @type {string}
     * @memberof ProductGroup
     */
    name?: string;
    /**
     * The number of the product group
     * @type {string}
     * @memberof ProductGroup
     */
    number?: string;
    /**
     * Unique id the product group
     * @type {string}
     * @memberof ProductGroup
     */
    productGroupId?: string;
}
