/* tslint:disable */
/* eslint-disable */
/**
 * business-data-api
 * business-data-api API definitions
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { VndError } from './vnd-error';
/**
 * 
 * @export
 * @interface VndErrors
 */
export interface VndErrors {
    /**
     * 
     * @type {{ [key: string]: Array<VndError>; }}
     * @memberof VndErrors
     */
    embedded?: { [key: string]: Array<VndError>; };
    /**
     * 
     * @type {number}
     * @memberof VndErrors
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof VndErrors
     */
    logref?: string;
    /**
     * 
     * @type {string}
     * @memberof VndErrors
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof VndErrors
     */
    request?: string;
    /**
     * 
     * @type {string}
     * @memberof VndErrors
     */
    service?: string;
    /**
     * 
     * @type {number}
     * @memberof VndErrors
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof VndErrors
     */
    timestamp?: string;
    /**
     * 
     * @type {any}
     * @memberof VndErrors
     */
    values?: any;
}
