/* tslint:disable */
/* eslint-disable */
/**
 * business-data-api
 * business-data-api API definitions
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CancelReason
 */
export interface CancelReason {
    /**
     * Unique id of the cancel reason
     * @type {string}
     * @memberof CancelReason
     */
    cancelReasonId?: string;
    /**
     * The name of the cancel reason
     * @type {string}
     * @memberof CancelReason
     */
    name?: string;
    /**
     * The number of the cancel reason
     * @type {string}
     * @memberof CancelReason
     */
    number?: string;
}
