/* tslint:disable */
/* eslint-disable */
/**
 * business-data-api
 * business-data-api API definitions
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DataInputMask } from './data-input-mask';
import { ManagedArticle } from './managed-article';
/**
 * 
 * @export
 * @interface DataEntry
 */
export interface DataEntry {
    /**
     * Unique id of the data entry
     * @type {string}
     * @memberof DataEntry
     */
    dataEntryId?: string;
    /**
     * 
     * @type {DataInputMask}
     * @memberof DataEntry
     */
    dataInputMask?: DataInputMask;
    /**
     * UTC-Timestamp when the data entry change occurred
     * @type {string}
     * @memberof DataEntry
     */
    inputAt?: string;
    /**
     * List of managed articles
     * @type {Array<ManagedArticle>}
     * @memberof DataEntry
     */
    managedArticles?: Array<ManagedArticle>;
    /**
     * Name of the pos user
     * @type {string}
     * @memberof DataEntry
     */
    posUserName?: string;
    /**
     * Number of the pos user
     * @type {number}
     * @memberof DataEntry
     */
    posUserNo?: number;
    /**
     * Serial number of the used cash register
     * @type {string}
     * @memberof DataEntry
     */
    serialNumber?: string;
}
