/* tslint:disable */
/* eslint-disable */
/**
 * business-data-api
 * business-data-api API definitions
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DataInputMaskColumn
 */
export interface DataInputMaskColumn {
    /**
     * The level of the input mask column
     * @type {number}
     * @memberof DataInputMaskColumn
     */
    columnLevel?: number;
    /**
     * The name of the input mask column
     * @type {string}
     * @memberof DataInputMaskColumn
     */
    columnName?: string;
    /**
     * The number of the input mask column
     * @type {number}
     * @memberof DataInputMaskColumn
     */
    columnNo?: number;
}
