/* tslint:disable */
/* eslint-disable */
/**
 * business-data-api
 * business-data-api API definitions
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InvoiceCanceledItem
 */
export interface InvoiceCanceledItem {
    /**
     * Cancel price of the item
     * @type {number}
     * @memberof InvoiceCanceledItem
     */
    cancelPrice?: number;
    /**
     * The id of the reason of the cancellation
     * @type {string}
     * @memberof InvoiceCanceledItem
     */
    cancelReasonId?: string;
    /**
     * Amount of discounts contained on canceled item
     * @type {number}
     * @memberof InvoiceCanceledItem
     */
    discountAmount?: number;
    /**
     * Unique id of the canceled item
     * @type {string}
     * @memberof InvoiceCanceledItem
     */
    invoiceCanceledItemId?: string;
    /**
     * The id of the parent canceled item
     * @type {string}
     * @memberof InvoiceCanceledItem
     */
    parentInvoiceCanceledItemId?: string;
    /**
     * Unique product id of the item
     * @type {string}
     * @memberof InvoiceCanceledItem
     */
    productId?: string;
    /**
     * Quantity of the item
     * @type {number}
     * @memberof InvoiceCanceledItem
     */
    quantity?: number;
    /**
     * Tax rate of the item
     * @type {number}
     * @memberof InvoiceCanceledItem
     */
    taxRate?: number;
}
