/* tslint:disable */
/* eslint-disable */
/**
 * business-data-api
 * business-data-api API definitions
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InvoiceItemDiscount
 */
export interface InvoiceItemDiscount {
    /**
     * Unique id of the discount
     * @type {string}
     * @memberof InvoiceItemDiscount
     */
    discountId?: string;
    /**
     * Unique id of the referencing invoice item
     * @type {string}
     * @memberof InvoiceItemDiscount
     */
    invoiceItemId?: string;
    /**
     * Human readable name of the discount
     * @type {string}
     * @memberof InvoiceItemDiscount
     */
    name?: string;
    /**
     * Human readable numeric identifier of the discount
     * @type {string}
     * @memberof InvoiceItemDiscount
     */
    number?: string;
    /**
     * Value of the discount
     * @type {number}
     * @memberof InvoiceItemDiscount
     */
    value?: number;
}
