/* tslint:disable */
/* eslint-disable */
/**
 * business-data-api
 * business-data-api API definitions
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InvoiceSurcharge
 */
export interface InvoiceSurcharge {
    /**
     * Human readable name of the surcharge
     * @type {string}
     * @memberof InvoiceSurcharge
     */
    name?: string;
    /**
     * Human readable numeric identifier of the surcharge
     * @type {string}
     * @memberof InvoiceSurcharge
     */
    number?: string;
    /**
     * Unique id of the surcharge
     * @type {string}
     * @memberof InvoiceSurcharge
     */
    surchargeId?: string;
    /**
     * Value of the surcharge
     * @type {number}
     * @memberof InvoiceSurcharge
     */
    value?: number;
}
