/* tslint:disable */
/* eslint-disable */
/**
 * business-data-api
 * business-data-api API definitions
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MainGroup
 */
export interface MainGroup {
    /**
     * Unique id the main group
     * @type {string}
     * @memberof MainGroup
     */
    mainGroupId?: string;
    /**
     * The name of the main group
     * @type {string}
     * @memberof MainGroup
     */
    name?: string;
    /**
     * The number of the main group
     * @type {string}
     * @memberof MainGroup
     */
    number?: string;
}
