/* tslint:disable */
/* eslint-disable */
/**
 * business-data-api
 * business-data-api API definitions
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Operator
 */
export interface Operator {
    /**
     * Operator name
     * @type {string}
     * @memberof Operator
     */
    name?: string;
    /**
     * Unique operator id
     * @type {string}
     * @memberof Operator
     */
    operatorId?: string;
}
