/* tslint:disable */
/* eslint-disable */
/**
 * business-data-api
 * business-data-api API definitions
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PartnerCredentials
 */
export interface PartnerCredentials {
    /**
     * User login
     * @type {string}
     * @memberof PartnerCredentials
     */
    login: string;
    /**
     * User password
     * @type {string}
     * @memberof PartnerCredentials
     */
    password: string;
}
