/* tslint:disable */
/* eslint-disable */
/**
 * business-data-api
 * business-data-api API definitions
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * The id of the main group a that is assigned to this product
     * @type {string}
     * @memberof Product
     */
    mainGroupId?: string;
    /**
     * The name of the product
     * @type {string}
     * @memberof Product
     */
    name?: string;
    /**
     * The number of the product
     * @type {string}
     * @memberof Product
     */
    number?: string;
    /**
     * The id of the product group that is assigned to this product
     * @type {string}
     * @memberof Product
     */
    productGroupId?: string;
    /**
     * Unique id the product
     * @type {string}
     * @memberof Product
     */
    productId?: string;
}
