/* tslint:disable */
/* eslint-disable */
/**
 * business-data-api
 * business-data-api API definitions
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Site
 */
export interface Site {
    /**
     * Site name
     * @type {string}
     * @memberof Site
     */
    name?: string;
    /**
     * Unique site id
     * @type {string}
     * @memberof Site
     */
    siteId?: string;
}
