/* tslint:disable */
/* eslint-disable */
/**
 * business-data-api
 * business-data-api API definitions
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface StaffAttendance
 */
export interface StaffAttendance {
    /**
     * Timestamp when the attendance change occurred
     * @type {string}
     * @memberof StaffAttendance
     */
    occurredAt?: string;
    /**
     * Serial number of the used cash register
     * @type {string}
     * @memberof StaffAttendance
     */
    serialNumber?: string;
    /**
     * Unique id for this attendance entry
     * @type {string}
     * @memberof StaffAttendance
     */
    staffAttendanceId?: string;
    /**
     * Name of the staff
     * @type {string}
     * @memberof StaffAttendance
     */
    staffName?: string;
    /**
     * Number of the staff
     * @type {number}
     * @memberof StaffAttendance
     */
    staffNumber?: number;
    /**
     * Attendance state
     * @type {string}
     * @memberof StaffAttendance
     */
    state?: StaffAttendanceStateEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum StaffAttendanceStateEnum {
    INFORMATION = 'INFORMATION',
    INTERRUPTION = 'INTERRUPTION',
    PAIDPAUSE = 'PAID_PAUSE',
    PAUSE = 'PAUSE',
    SIGNINASCASHIER = 'SIGN_IN_AS_CASHIER',
    SIGNINASWORKER = 'SIGN_IN_AS_WORKER',
    SIGNOFF = 'SIGN_OFF'
}

